import { useState, createContext } from "react";

export const DataContext = createContext();

export const DataProvider = (props) => {
  const [todoState, setTodoState] = useState({
    category: [
      {
        category_name: "Personal",
        category_id: 1,
      },
      {
        category_name: "Learning",
        category_id: 2,
      },
      {
        category_name: "Project",
        category_id: 3,
      },
    ],
    sub_category: [
      {
        category_id: 1,
        sub_category_id: 1,
        category_name: "Personal",
        sub_category_name: "Fitness",
      },
      {
        category_id: 1,
        sub_category_id: 2,
        category_name: "Personal",
        sub_category_name: "Health & food diet",
      },
      {
        category_id: 1,
        sub_category_id: 3,
        category_name: "Personal",
        sub_category_name: "Meeting",
      },
      {
        category_id: 2,
        sub_category_id: 4,
        category_name: "Learning",
        sub_category_name: "ReadingBlogs",
      },
      {
        category_id: 2,
        sub_category_id: 5,
        category_name: "Learning",
        sub_category_name: "Meetups",
      },
      {
        category_id: 2,
        sub_category_id: 6,
        category_name: "Learning",
        sub_category_name: "Analysis design",
      },
      {
        category_id: 2,
        sub_category_id: 7,
        category_name: "Learning",
        sub_category_name: "Design revisit",
      },
      {
        category_id: 3,
        sub_category_id: 8,
        category_name: "Project",
        sub_category_name: "Client Calls",
      },
      {
        category_id: 3,
        sub_category_id: 9,
        category_name: "Project",
        sub_category_name: "second Client Calls",
      },
      {
        category_id: 3,
        sub_category_id: 10,
        category_name: "Project",
        sub_category_name: "Pending Works",
      },
      {
        category_id: 3,
        sub_category_id: 11,
        category_name: "Project",
        sub_category_name: "Completed Works",
      },
    ],
    task: [
      {
        id: "1",
        category_id: 1,
        sub_category_id: 1,
        category: "Personal",
        subCategory: "Fitness",
        title: "Bring essentials for kitchen13",
        settingForDate: "20-20-2020",
        setting_on_Which_date: "20-20-2*2*",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "deleted",
      },
      {
        id: "2",
        category_id: 1,
        sub_category_id: 1,
        category: "Personal",
        subCategory: "Health & food diet",
        title: "Bring essentials for daily Diet12",
        settingForDate: "21-20-2020",
        setting_on_Which_date: "20-20-2*2*",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "completed",
      },
      {
        id: "3",
        category_id: 1,
        sub_category_id: 1,
        category: "Personal",
        subCategory: "Meeting",
        title: "Bring essentials for Meeting11",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "4",
        category_id: 2,
        sub_category_id: 2,
        category: "Learning",
        subCategory: "ReadingBlogs",
        title: "read Blogs to enhanse reading10",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "5",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "Client Calls",
        title: "so many client calls9",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "7",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "second Client Calls",
        title: "many many many client calls8",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "8",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "second Client Calls",
        title: "many many many client calls7",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "9",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "second Client Calls",
        title: "many many many client calls6",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "10",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "second Client Calls",
        title: "many many many client calls5",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "11",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "second Client Calls",
        title: "many many many client calls4",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "12",
        category_id: 3,
        sub_category_id: 3,
        category: "Project",
        subCategory: "second Client Calls",
        title: "many many many client calls3",
        settingForDate: "20-20-2020",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "upcoming",
      },
      {
        id: "13",
        category_id: 1,
        sub_category_id: 1,
        category: "Personal",
        subCategory: "Health & food diet",
        title: "Bring essentials for daily Diet2",
        settingForDate: "21-20-2020",
        setting_on_Which_date: "20-20-2*2*",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "completed",
      },
      {
        id: "14",
        category_id: 1,
        sub_category_id: 1,
        category: "Personal",
        subCategory: "Fitness",
        title: "Bring essentials for kitchen1",
        settingForDate: "20-20-2020",
        setting_on_Which_date: "20-20-2*2*",
        setting_on_what_time: "",
        setting_for_what_time: "12:30",
        whatsTheStatus: "deleted",
      },
    ],
    search: "",
    typeOfStatus: ["upcoming", "completed", "deleted"],
  });
  return (
    <DataContext.Provider value={[todoState, setTodoState]}>
      {props.children}
    </DataContext.Provider>
  );
};
